package com.mugsun.boot.gis;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * 要素行回填的并发正确性。本类自带 PostGIS 容器（基座那套是 postgres:16-alpine，没有扩展，
 * 测不了下沉路径），只为守住一件事：**同一图层被并发首枪打中时，要素行数必须精确等于要素数**。
 *
 * <p>这条用例是从性能基线里挖出来的真实缺陷回归：原实现的「先 DELETE 再分批 INSERT」各自独立提交，
 * 并发时互相穿插——A 删完正插一半，B 又删（把 A 已插的删掉）再插，最终留下随机数量的重复行。
 * 实测 8 并发首枪把 8000 要素灌成 62235 行，此后所有空间查询都返回重复要素。
 */
class GisFeatureStoreConcurrencyTest {

	private static final int FEATURES = 300;
	private static final long LAYER_ID = 900001L;
	private static final String TENANT = "000000";

	private static PostgreSQLContainer<?> postgis;
	private static JdbcTemplate jdbc;

	private GisFeatureStore store;

	@BeforeAll
	static void startDb() {
		postgis = new PostgreSQLContainer<>(
			DockerImageName.parse("postgis/postgis:16-3.4")
				.asCompatibleSubstituteFor("postgres"))
			.withDatabaseName("mugsun")
			.withUsername("mugsun")
			.withPassword("mugsun");
		postgis.start();

		DriverManagerDataSource ds = new DriverManagerDataSource(
			postgis.getJdbcUrl(), postgis.getUsername(), postgis.getPassword());
		ds.setDriverClassName("org.postgresql.Driver");
		jdbc = new JdbcTemplate(ds);
		jdbc.execute("CREATE EXTENSION IF NOT EXISTS postgis");
		// 与 V79 的 gis_feature 同构（省掉与本用例无关的注释与租户索引）
		jdbc.execute("""
			CREATE TABLE gis_feature (
				id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				tenant_id   VARCHAR(12),
				layer_id    BIGINT NOT NULL,
				geom        geometry(Geometry, 4326) NOT NULL,
				props_json  TEXT,
				create_time TIMESTAMP,
				update_time TIMESTAMP,
				is_deleted  INT NOT NULL DEFAULT 0
			)
			""");
		jdbc.execute("CREATE INDEX idx_gis_feature_geom ON gis_feature USING GIST (geom)");
	}

	@AfterAll
	static void stopDb() {
		if (postgis != null) {
			postgis.stop();
		}
	}

	@BeforeEach
	void setUp() {
		GisSpatialSupport support = mock(GisSpatialSupport.class);
		when(support.available()).thenReturn(true);
		when(support.jdbc()).thenReturn(jdbc);
		store = new GisFeatureStore(support, new ObjectMapper());
		jdbc.update("DELETE FROM gis_feature WHERE layer_id = ?", LAYER_ID);
	}

	@Test
	@DisplayName("并发首枪回填：要素行数精确等于要素数，不出重复行")
	void concurrentBackfillLandsExactlyOnce() throws Exception {
		String data = featureCollection();
		int threads = 8;
		ExecutorService pool = Executors.newFixedThreadPool(threads);
		try {
			List<Callable<Integer>> jobs = new ArrayList<>();
			for (int i = 0; i < threads; i++) {
				jobs.add(() -> store.backfillIfEmpty(LAYER_ID, TENANT, GisConstants.KIND_VECTOR, data));
			}
			for (Future<Integer> f : pool.invokeAll(jobs)) {
				// 每个调用都要拿到「完整的要素行数」，不能有人看到半成品
				assertThat(f.get()).isEqualTo(FEATURES);
			}
		} finally {
			pool.shutdownNow();
		}
		assertThat(rowCount()).isEqualTo(FEATURES);
	}

	@Test
	@DisplayName("并发重建（图层被反复保存）：最终行数仍精确等于要素数")
	void concurrentRebuildIsAtomic() throws Exception {
		String data = featureCollection();
		store.sync(LAYER_ID, TENANT, GisConstants.KIND_VECTOR, data);

		int threads = 8;
		ExecutorService pool = Executors.newFixedThreadPool(threads);
		try {
			List<Callable<Integer>> jobs = new ArrayList<>();
			for (int i = 0; i < threads; i++) {
				jobs.add(() -> store.sync(LAYER_ID, TENANT, GisConstants.KIND_VECTOR, data));
			}
			for (Future<Integer> f : pool.invokeAll(jobs)) {
				assertThat(f.get()).isEqualTo(FEATURES);
			}
		} finally {
			pool.shutdownNow();
		}
		assertThat(rowCount()).isEqualTo(FEATURES);
	}

	@Test
	@DisplayName("回填期间的读者看不到半成品：要么 0 行，要么全量")
	void readersNeverSeePartialRows() throws Exception {
		String data = featureCollection();
		ExecutorService pool = Executors.newFixedThreadPool(2);
		try {
			Future<Integer> writer = pool.submit(
				() -> store.backfillIfEmpty(LAYER_ID, TENANT, GisConstants.KIND_VECTOR, data));
			Future<List<Integer>> reader = pool.submit(() -> {
				List<Integer> seen = new ArrayList<>();
				for (int i = 0; i < 60; i++) {
					seen.add(rowCount());
					Thread.sleep(2);
				}
				return seen;
			});
			assertThat(writer.get()).isEqualTo(FEATURES);
			assertThat(reader.get()).allSatisfy(n -> assertThat(n).isIn(0, FEATURES));
		} finally {
			pool.shutdownNow();
		}
	}

	/**
	 * 批量插入撞上 PostGIS 拒收的几何时，整批会失败并把事务标记为异常。这里守的是保存点回滚
	 * 有没有生效——没有的话后续语句全被事务的异常状态挡住，好要素也一条都进不去。
	 *
	 * <p>坏样本用「未知几何类型」而不是坏坐标：PostGIS 对坐标极其宽容，
	 * {@code ["坏","数据"]} 会被静默当成 0 存成 POINT(0 0) 而不报错（入站侧由
	 * {@link GisTopologyGuard} 拦，这里只测存储层的事务行为）。
	 */
	@Test
	@DisplayName("批内有 PostGIS 拒收的几何：坏要素跳过，好要素照常落库")
	void rejectedGeometryIsSkippedNotFatal() {
		String data = """
			{"type":"FeatureCollection","features":[
			 {"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[116.4,39.9]}},
			 {"type":"Feature","properties":{},"geometry":{"type":"Circle","coordinates":[116.45,39.95]}},
			 {"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[116.5,39.8]}}
			]}
			""";
		assertThat(store.sync(LAYER_ID, TENANT, GisConstants.KIND_VECTOR, data)).isEqualTo(2);
		assertThat(rowCount()).isEqualTo(2);
	}

	private int rowCount() {
		Integer n = jdbc.queryForObject(
			"SELECT count(*) FROM gis_feature WHERE layer_id = ?", Integer.class, LAYER_ID);
		return n == null ? 0 : n;
	}

	/** 北京城区范围内撒 FEATURES 个点，够多才能让并发穿插有机会发生 */
	private static String featureCollection() {
		StringBuilder sb = new StringBuilder("{\"type\":\"FeatureCollection\",\"features\":[");
		for (int i = 0; i < FEATURES; i++) {
			if (i > 0) {
				sb.append(',');
			}
			double lon = 116.3 + (i % 50) * 0.004;
			double lat = 39.85 + (i / 50) * 0.004;
			sb.append("{\"type\":\"Feature\",\"properties\":{\"no\":").append(i)
				.append("},\"geometry\":{\"type\":\"Point\",\"coordinates\":[")
				.append(lon).append(',').append(lat).append("]}}");
		}
		return sb.append("]}").toString();
	}
}
