-- 要素行表：把整层 GeoJSON（gis_layer.data_json）拆成一要素一行，落真实 geometry 列 + GiST 索引，
-- 让「视野范围内 / 半径内 / 与某面相交 / 最近邻」四类高频查询能下沉数据库，不再全量捞回 Java 遍历。
--
-- 两点刻意设计：
-- 1) 全部包在 DO 块里。没装 PostGIS 的库（含达梦，转换器会把 DO 块整段跳过）不建表也不报错，
--    应用层按 gis_feature 是否存在决定走下沉查询还是回落 data_json 的 Java 路径。
-- 2) gis_layer.data_json 保持不动。要素行是「加速副本」而非唯一真相，回填失败不影响既有读写。

DO $$
BEGIN
	CREATE EXTENSION IF NOT EXISTS postgis;
EXCEPTION WHEN OTHERS THEN
	RAISE NOTICE 'PostGIS 扩展不可用（%），gis_feature 不创建，GIS 空间查询回落 Java 侧', SQLERRM;
END $$;

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'postgis') THEN
		RETURN;
	END IF;

	EXECUTE '
		CREATE TABLE IF NOT EXISTS gis_feature (
			id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			tenant_id    VARCHAR(12),
			layer_id     BIGINT        NOT NULL,
			geom         geometry(Geometry, 4326) NOT NULL,
			props_json   TEXT,
			create_time  TIMESTAMP,
			update_time  TIMESTAMP,
			is_deleted   INT           NOT NULL DEFAULT 0
		)';

	EXECUTE 'CREATE INDEX IF NOT EXISTS idx_gis_feature_geom ON gis_feature USING GIST (geom)';
	EXECUTE 'CREATE INDEX IF NOT EXISTS idx_gis_feature_layer ON gis_feature (layer_id) WHERE is_deleted = 0';
	EXECUTE 'CREATE INDEX IF NOT EXISTS idx_gis_feature_tenant ON gis_feature (tenant_id) WHERE is_deleted = 0';

	EXECUTE 'COMMENT ON TABLE gis_feature IS ''GIS 要素行（WGS84 geometry + GiST，gis_layer.data_json 的空间查询加速副本）''';
	EXECUTE 'COMMENT ON COLUMN gis_feature.geom IS ''EPSG:4326，与 gis_layer.crs 同口径''';
	EXECUTE 'COMMENT ON COLUMN gis_feature.props_json IS ''GeoJSON Feature 的 properties 原文''';
END $$;
